---
# tasks file for containers

- name: Install Docker Python SDK
  pip:
    name: docker
    state: present

- name: Install Docker.io in Debian/Ubuntu
  apt:
    name: docker.io
    state: present
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Install dnf-plugins-core
  yum:
    name: dnf-plugins-core
    state: present
  when: ansible_facts['os_family'] == "RedHat" 

- name: Add Docker DNF Repo
  yum_repository:
    name: Docker.io
    description: Docker CE repo
    baseurl: https://download.docker.com/linux/fedora/31/x86_64/stable/
    gpgcheck: no

- name: Install dnf-plugins-core
  yum:
    name: docker-ce,docker-ce-cli,containerd.io
    state: present
  when: ansible_facts['os_family'] == "RedHat" 

#- name: Install Docker-ce via script
#  shell: curl https://get.docker.com | sh --
#  when: ansible_facts['os_family'] == "RedHat" 

- name: Enable required kernel modules - Debian/Ubuntu
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'modules', dest: '/etc/modules' }
  when: ansible_facts['os_family'] == "Debian"

- name: Enable required kernel modules - Red Hat/RedHat
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'modules', dest: '/etc/modules-load.d/k8s.conf' }
  when: ansible_facts['os_family'] == "RedHat"

- name: Load modules right now
  systemd:
    name: systemd-modules-load
    state: restarted

- name: Enable required kernel parameters
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes 

- name: Enable required kernel parameters
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes 

#- include_tasks: roles/containers/tasks/fedora.yaml
- include_tasks: fedora.yaml
  when: ansible_facts['os_family'] == "RedHat"
