---
# tasks file for swmanagement

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update hosts
  template:
    src=hosts.j2
    dest=/etc/hosts

- name: Customize motd
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'issue', dest: '/etc/issue' }
    - { src: 'issue.net', dest: '/etc/issue.net' }
    - { src: 'motd', dest: '/etc/motd' }

- name: Update APT
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Update OS
  apt:
    name: '*'
    state: latest
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Install curl, wget, vim, tmux,nc, git, Python, neofetch
  apt:
    name: curl,wget,vim,tmux,netcat-openbsd,git,python3,python-pip,neofetch
    state: present
    force_apt_get: True
  when: ansible_facts['os_family'] == "Debian"

- name: Upgrade system
  yum:
    name: '*'
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Git, tcpdump, nc,curl, wget, tmux, python3, python-setuptools and vim
  yum:
    name: curl,wget,vim,git,nmap-ncat,tcpdump,python-setuptools,python3
    state: present
  when: ansible_facts['os_family'] == "RedHat" 
  #when: ansible_distribution == 'Fedora'
  #when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
